#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

use_libs = ['ecell4-core']  # common
#use_libs.append('lboost_unit_test_framework')
#use_libs.append('lboost_test_exec_monitor')

def build(bld):
    bld.program(
        features = 'cxx cxxprogram test',
        source = 'Position3_test.cpp',
        includes = '..',
        target = 'Position3_test',
        defines = ['BOOST_TEST_DYN_LINK'],
        lib = ['gsl', 'gslcblas', 'm', 'boost_unit_test_framework'],
        use = use_libs,
    )

    bld.program(
        features = 'cxx cxxprogram test',
        source = 'CompartmentSpace_test.cpp',
        includes = '..',
        defines = ['BOOST_TEST_DYN_LINK'],
        target = 'CompartmentSpace_test',
        lib = ['gsl', 'gslcblas', 'm',
               'hdf5_hl_cpp', 'hdf5_cpp', 'hdf5_hl', 'hdf5', 'boost_unit_test_framework'],
        use = use_libs,
    )

    bld.program(
        features = 'cxx cxxprogram test',
        source = 'Species_test.cpp',
        includes = '..',
        defines = ['BOOST_TEST_DYN_LINK'],
        target = 'Species_test',
        lib = ['gsl', 'gslcblas', 'm', 'boost_unit_test_framework'],
        use = use_libs,
    )

    bld.program(
        features = 'cxx cxxprogram test',
        source = 'ReactionRule_test.cpp',
        includes = '..',
        defines = ['BOOST_TEST_DYN_LINK'],
        target = 'ReactionRule_test',
        lib = ['gsl', 'gslcblas', 'm', 'boost_unit_test_framework'],
        use = use_libs
    )

    bld.program(
        features = 'cxx cxxprogram test',
        source = 'NetworkModel_test.cpp',
        includes = '..',
        defines = ['BOOST_TEST_DYN_LINK'],
        target = 'NetworkModel_test',
        lib = ['gsl', 'gslcblas', 'm', 'boost_unit_test_framework'],
        use = use_libs,
    )

    bld.program(
        features = 'cxx cxxprogram test',
        source = 'get_mapper_mf_test.cpp',
        includes = '..',
        defines = ['BOOST_TEST_DYN_LINK'],
        target = 'get_mapper_mf_test',
        lib = ['gsl', 'gslcblas', 'm', 'boost_unit_test_framework'],
        use = use_libs,
    )
